// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40pom3AlQ_Va9NANrZTxldndvJsrQGVQ',
    appId: '1:625508812514:web:e2c552503d45c05d9280bb',
    messagingSenderId: '625508812514',
    projectId: 'kanban-manager-mobile',
    authDomain: 'kanban-manager-mobile.firebaseapp.com',
    storageBucket: 'kanban-manager-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZMpbjIVwZQyKB8hLRo7YMAJwNEWneOo',
    appId: '1:625508812514:android:ec905a4124dcb76d9280bb',
    messagingSenderId: '625508812514',
    projectId: 'kanban-manager-mobile',
    storageBucket: 'kanban-manager-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBwvlyJ5aVACuA-sy-pSwuK3XcjjrkFT4',
    appId: '1:625508812514:ios:10b5ec1ebe8454d69280bb',
    messagingSenderId: '625508812514',
    projectId: 'kanban-manager-mobile',
    storageBucket: 'kanban-manager-mobile.appspot.com',
    iosClientId: '625508812514-t92m6o2qtns7fd8aileedslcq870uai2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanban',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBwvlyJ5aVACuA-sy-pSwuK3XcjjrkFT4',
    appId: '1:625508812514:ios:10b5ec1ebe8454d69280bb',
    messagingSenderId: '625508812514',
    projectId: 'kanban-manager-mobile',
    storageBucket: 'kanban-manager-mobile.appspot.com',
    iosClientId: '625508812514-t92m6o2qtns7fd8aileedslcq870uai2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanban',
  );
}
